//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gw2AddonsUpdaterLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gw2AddonsUpdaterLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://martionlabs.com/wp-content/uploads/d3d9_arcdps_mechanics.dll.
        /// </summary>
        internal static string ArcdpsMechanicsURi {
            get {
                return ResourceManager.GetString("ArcdpsMechanicsURi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://martionlabs.com/wp-content/uploads/d3d9_arcdps_mechanics.dll.md5sum.
        /// </summary>
        internal static string ArcdpsMechanicsURiMD5 {
            get {
                return ResourceManager.GetString("ArcdpsMechanicsURiMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bin64\.
        /// </summary>
        internal static string ArcdpsPath {
            get {
                return ResourceManager.GetString("ArcdpsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://www.deltaconnected.com/arcdps/x64/buildtemplates/d3d9_arcdps_buildtemplates.dll.
        /// </summary>
        internal static string ArcdpsTemplatesUri {
            get {
                return ResourceManager.GetString("ArcdpsTemplatesUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://www.deltaconnected.com/arcdps/x64/d3d9.dll.
        /// </summary>
        internal static string ArcdpsURi {
            get {
                return ResourceManager.GetString("ArcdpsURi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://www.deltaconnected.com/arcdps/x64/d3d9.dll.md5sum.
        /// </summary>
        internal static string ArcdpsURiMD5 {
            get {
                return ResourceManager.GetString("ArcdpsURiMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à addons\.
        /// </summary>
        internal static string Gw2AddonPath {
            get {
                return ResourceManager.GetString("Gw2AddonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\Program Files\Guild Wars 2\.
        /// </summary>
        internal static string Gw2Path {
            get {
                return ResourceManager.GetString("Gw2Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à taco\.
        /// </summary>
        internal static string TacoPath {
            get {
                return ResourceManager.GetString("TacoPath", resourceCulture);
            }
        }
    }
}
